- name: Configure Machine Credentials using Vault Signed SSH
  ansible.controller.credential:
    name: "minecraft_ssh_credentials"                  # Name of the credential
    description: "Credentials for Minecraft SSH"       # Description of the credential
    organization: "{{ item.name }}"                     # Organization name in AAP
    credential_type: "Machine"                          # Type of the credential
    state: present                                      # Ensures the credential is updated or created if absent
    inputs:                                             # All required fields for this credential type
     username: ubuntu                                      
    controller_host: "{{ aap_url }}"                    # URL of your AAP instance
    controller_username: "admin"                        # AAP username
    controller_password: "{{ aap_password }}"           # AAP password
    validate_certs: false                               # Skip SSL verification if using self-signed certs
  loop: "{{ aap_organizations }}"
  register: ssh_machine_credentials

- name: Debug ssh_machine_credentials
  debug:
    var: ssh_machine_credentials