- name: Ansible Automation Platform
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Add osquery repo key
      get_url:
        url: https://pkg.osquery.io/deb/pubkey.gpg
        dest: /usr/share/keyrings/osquery.asc
        mode: 0644

    - name: Add osquery repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/osquery.asc] https://pkg.osquery.io/deb deb main
        state: present
        mode: 0666

    - name: Add docker repo key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.asc
        mode: 0644

    - name: Add docker repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/docker-archive-keyring.asc] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        mode: 0666

    ## Vault SSH signing CA
    - name: Create temporary directory for SSH CA storage
      file:
        path: /tmp/ssh_ca.d/
        state: directory

    - name: Add HCP Vault SSH signing public certificate
      get_url:
        url: https://skoaap-public-vault-8683511a.d19fbab7.z1.hashicorp.cloud:8200/v1/ssh/public_key
        headers: 
          X-Vault-Namespace: "admin/{{ lookup('env', 'VAULT_NAMESPACE') }}"
        dest: /tmp/ssh_ca.d/hcp-vault-ca-keys.pem
        mode: 0644
        
    - name: Add CA public certificates
      assemble:
        src: /tmp/ssh_ca.d/
        dest: /etc/ssh/trusted-user-ca-keys.pem

    - name: Update ssh config
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem

    - name: Register HCP Vault CA
      command: update-ca-certificates