
    - name: Add docker repo key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.asc
        mode: 0644

    - name: Add docker repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/docker-archive-keyring.asc] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        mode: 0666

    - name: "Install Docker packages"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes  # this will refresh your repository cache

    - name: "Docker Service"
      systemd:
        name: docker.service
        enabled: yes
        state: started
        
    - name: Add user 'ubuntu' to the 'docker' group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
      become: true

      # - name: Add osquery repo key
      #   get_url:
      #     url: https://pkg.osquery.io/deb/pubkey.gpg
      #     dest: /usr/share/keyrings/osquery.asc
      #     mode: 0644

      # - name: Add osquery repository
      #   apt_repository:
      #     repo: deb [signed-by=/usr/share/keyrings/osquery.asc] https://pkg.osquery.io/deb deb main
      #     state: present
      #     mode: 0666