- name: Ansible Automation Platform
  hosts: all
  become: true
  gather_facts: false
  collections:
    - community.docker
  tasks:
  - name: "Start docker container"
    community.docker.docker_container:
      name: my-container
      image: "{{ docker_image }}"
      state: started
      ports:
        - "80:80"
      restart_policy: unless-stopped