---
# AAP Gateway URL
aap_url: "https://44.210.128.100"

# Hashicorp Vault Public URL
vault_url: "https://skoaap-public-vault-8683511a.d19fbab7.z1.hashicorp.cloud:8200"

# SSH Secrets Engine Configuration
vault_ssh_mount_point: "ssh"  # Default SSH secrets engine mount point
vault_ssh_role: "aap"  # Role for SSH signed certificates
vault_root_ca: "-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
-----END CERTIFICATE-----"

# Organizations and Users
aap_organizations:
- name: terraformtitans
  state: exists
  namespace: "terraformtitans"
- name: vaultvillagers
  state: exists
  namespace: "vaultvillagers"
- name: consulcreepers
  state: exists
  namespace: "consulcreepers"
- name: nomadnethers
  state: exists
  namespace: "nomadnethers"
- name: boundaryblazes
  state: exists
  namespace: "boundaryblazes"
- name: waypointwithers
  state: exists
  namespace: "waypointwithers"
- name: packerpiglins
  state: exists
  namespace: "packerpiglins"
- name: diamonddevops
  state: exists
  namespace: "diamonddevops"
- name: redstonerunners
  state: exists
  namespace: "redstonerunners"
- name: vagrantvexes
  state: exists
  namespace: "vagrantvexes"
- name: obsidianoperators
  state: exists
  namespace: "obsidianoperators"
- name: endermanengineers
  state: exists
  namespace: "endermanengineers"
- name: cloudguards
  state: exists
  namespace: "cloudguards"
- name: cloudcrafters
  state: exists
  namespace: "cloudcrafters"
- name: pipelinepillagers
  state: exists
  namespace: "pipelinepillagers"
- name: terraformtowers
  state: exists
  namespace: "terraformtowers"
- name: statestorrageslimes
  state: exists
  namespace: "statestorrageslimes"
- name: moduleminers
  state: exists
  namespace: "moduleminers"
- name: sentinelshulkers
  state: exists
  namespace: "sentinelshulkers"
- name: resourceravagers
  state: exists
  namespace: "resourceravagers"
- name: configzombies
  state: exists
  namespace: "configzombies"
- name: secretskeletons
  state: exists
  namespace: "secretskeletons"
- name: registryraiders
  state: exists
  namespace: "registryraiders"
- name: clustercrystals
  state: exists
  namespace: "clustercrystals"
- name: chaincraft
  state: exists
  namespace: "chaincraft"
- name: netherdrakes
  state: exists
  namespace: "netherdrakes"
- name: stackspiders
  state: exists
  namespace: "stackspiders"
- name: swiftaxols
  state: exists
  namespace: "swiftaxols"
- name: provisionphantoms
  state: exists
  namespace: "provisionphantoms"
- name: platformpandas
  state: exists
  namespace: "platformpandas"
- name: networknetherite
  state: exists
  namespace: "networknetherite"
- name: securitystriders
  state: exists
  namespace: "securitystriders"
- name: orchaminers
  state: exists
  namespace: "orchaminers"
- name: containercopper
  state: exists
  namespace: "containercopper"
- name: databasedrowned
  state: exists
  namespace: "databasedrowned"
- name: servicesilverfish
  state: exists
  namespace: "servicesilverfish"
- name: policyparrots
  state: exists
  namespace: "policyparrots"
- name: meshmagma
  state: exists
  namespace: "meshmagma"
- name: dockerdolphins
  state: exists
  namespace: "dockerdolphins"
- name: pipelinepiglins
  state: exists
  namespace: "pipelinepiglins"
- name: testorga
  state: exists
  namespace: "testorga"
- name: testorgb
  state: exists
  namespace: "testorgb"
- name: testorgc
  state: exists
  namespace: "testorgc"
- name: testorgd
  state: exists
  namespace: "testorgd"
- name: testorge
  state: exists
  namespace: "testorge"
- name: testorgf
  state: exists
  namespace: "testorgf"
- name: testorgg
  state: exists
  namespace: "testorgg"
- name: testorgh
  state: exists
  namespace: "testorgh"
- name: testorgi
  state: exists
  namespace: "testorgi"
- name: testorgj
  state: exists
  namespace: "testorgj"
- name: testorgk
  state: exists
  namespace: "testorgk"
- name: testorgl
  state: exists
  namespace: "testorgl"
- name: testorgm
  state: exists
  namespace: "testorgm"
- name: testorgn
  state: exists
  namespace: "testorgn"
- name: testorgo
  state: exists
  namespace: "testorgo"
- name: testorgp
  state: exists
  namespace: "testorgp"
- name: testorgq
  state: exists
  namespace: "testorgq"
- name: testorgr
  state: exists
  namespace: "testorgr"
- name: testorgs
  state: exists
  namespace: "testorgs"
- name: testorgt
  state: exists
  namespace: "testorgt"
- name: testorgu
  state: exists
  namespace: "testorgu"
- name: testorgv
  state: exists
  namespace: "testorgv"
- name: testorgw
  state: exists
  namespace: "testorgw"
- name: testorgx
  state: exists
  namespace: "testorgx"
- name: testorgy
  state: exists
  namespace: "testorgy"
- name: testorgz
  state: exists
  namespace: "testorgz"

projects:
  - name: "minecraft_config"
    description: "Mindcraft configuration project"
    state: exists
    scm_type: "git"
    scm_url: "https://github.com/hashi-demo-lab/sko_aap_deployment_aws"
    scm_branch: "main"
