---
- name: Update whitelist.conf with unique blocks
  hosts: all
  become: yes
  vars:
    whitelist_users:
      - "username1"
      - "username2"
      - "username3"
  tasks:
    - name: Ensure whitelist.conf exists
      file:
        path: /etc/minecraft/whitelist.conf
        state: touch

    - name: Add users to whitelist.conf (if not already present)
      blockinfile:
        path: /etc/minecraft/whitelist.conf
        block: |
          {{ item }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ item }}"
        create: yes
      loop: "{{ whitelist_users }}"