---
- name: Update whitelist.conf with unique blocks
  hosts: all
  vars:
    whitelist_users:
      - "username1"
      - "username2"
      - "username3"
  tasks:
    - name: Ensure whitelist.conf exists
      ansible.builtin.file:
        path: /etc/minecraft/whitelist.conf
        state: touch
        
    - name: Check if lock file exists
      ansible.builtin.stat:
        path: /etc/minecraft/whitelist.lock
      register: lockfile

    - name: Fail if lock file exists
      ansible.builtin.fail:
        msg: "Another process is updating the file. Please try again later."
      when: lockfile.stat.exists

    - name: Create lock file
      ansible.builtin.file:
        path: /etc/minecraft/whitelist.lock
        state: touch
      when: not lockfile.stat.exists

    - name: Update the target file
      lineinfile:
        path: /etc/minecraft/whitelist.conf
        line: "New content to add or update"
        state: present
    - name: Remove lock file
      file:
        path: /etc/minecraft/whitelist.lock
        state: absent
      when: not lockfile.stat.exists