- name: Give users organization admin role
  ansible.platform.role_user_assignment:
    role_definition: Organization Admin
    user: "{{ item.name }}_admin"
    state: present
    gateway_hostname: "{{ aap_url }}"
    gateway_username: "admin"
    gateway_password: "{{ aap_password }}"
    gateway_validate_certs: false
  loop: "{{ aap_organizations }}"