- name: Create Organization Admin Role
  ansible.controller.role:
    users: 
    - "{{ item.name }}_admin"
    role: "Organization Admin"
    organizations: 
    - "{{ item.name }}"
    state: present
    controller_host: "{{ aap_url }}"
    controller_username: "admin"
    controller_password: "{{ aap_password }}"
    validate_certs: False
  loop: "{{ aap_organizations }}"