- name: Create Organization Admin Role
  ansible.controller.role:
    name: org_admin_role
    role: member
    organization: "{{ item.name }}"
    description: "Full access within organization boundary"
    permissions: "{{ org_admin_permissions }}"
    state: present
    controller_host: "{{ aap_url }}"
    controller_username: "admin"
    controller_password: "{{ aap_password }}"
    validate_certs: False
  loop: "{{ aap_organizations }}"