- name: Create Organization Admin Role
  ansible.controller.role:
    user: "{{ item.name }}_admin"
    role: admin
    organization: "{{ item.name }}"
    state: present
    controller_host: "{{ aap_url }}"
    controller_username: "admin"
    controller_password: "{{ aap_password }}"
    validate_certs: False
  loop: "{{ aap_organizations }}"