---
  - name: Add user as a org administrator user
    ansible.platform.user:
      username: "{{ item.name }}_admin"
      password: foobarbaz
      organizations: "{{created_orgs.results}}[{{ item.name }}].id"
      state: present
    loop: "{{ aap_organizations }}"