---
  - name: Add user as a org administrator user
    ansible.platform.user:
      username: "{{ item.name }}_admin"
      password: foobarbaz
      organizations: "{{created_orgs.results}}[{{ item.name }}].id"
      state: present
      gateway_hostname: "{{ aap_url }}"
      gateway_username: "admin"
      gateway_password: "{{ aap_password }}"
      gateway_validate_certs: false
    loop: "{{ aap_organizations }}"