---
  - name: Debug org_map
    debug:
      var: org_map
  - name: create user 
    ansible.platform.user:
      username: "{{ item.name }}_admin"
      password: foobarbaz
      gateway_hostname: "{{ aap_url }}"
      gateway_username: "admin"
      gateway_password: "{{ aap_password }}"
      gateway_validate_certs: false
    loop: "{{ aap_organizations }}"
    register: created_users
  

  ### there appears to be a bug in the ansible.platform.user module that prevents the user from being added to the organization
  ### TO DO user association with organization POST a list of instances to /:id/users/associate/ to add those users to the relationship
  ### see https://44.210.128.100/api/gateway/v1/organizations/5/users/associate/

  # - name: Add user user to org
  #   ansible.platform.user:
  #     username: "{{ item.name }}_admin"
  #     password: foobarbaz
  #     email: "admin@gateway.hashicorp.com"
  #     organizations: 
  #       - '{{ org_map[ item.name ] }}'
  #     gateway_hostname: "{{ aap_url }}"
  #     gateway_username: "admin"
  #     gateway_password: "{{ aap_password }}"
  #     gateway_validate_certs: false
  #   loop: "{{ aap_organizations }}"
  #   register: created_users_updated
    
  # - name: Debug created_users
  #   debug:
  #     var: created_users