---
  - name: Debug org_map
    debug:
      var: org_map
  - name: create user 
    ansible.platform.user:
      username: "{{ item.name }}_admin"
      password: foobarbaz
      gateway_hostname: "{{ aap_url }}"
      gateway_username: "admin"
      gateway_password: "{{ aap_password }}"
      gateway_validate_certs: false
    loop: "{{ aap_organizations }}"
    register: created_users
  
  - name: Add user user to org
    ansible.platform.user:
      username: "{{ item.name }}_admin"
      password: foobarbaz
      organizations: 
        - '{{ org_map[ item.name ] }}'
      gateway_hostname: "{{ aap_url }}"
      gateway_username: "admin"
      gateway_password: "{{ aap_password }}"
      gateway_validate_certs: false
    loop: "{{ aap_organizations }}"
    register: created_users_updated
    
  - name: Debug created_users
    debug:
      var: created_users