---
  - name: Debug org_map
    debug:
      var: org_map
  - name: Add user as a org administrator user
    ansible.platform.user:
      username: "{{ item.name }}_admin"
      password: foobarbaz
      organizations: ["{{ org_map[item.name] }}"]
      state: present
      gateway_hostname: "{{ aap_url }}"
      gateway_username: "admin"
      gateway_password: "{{ aap_password }}"
      gateway_validate_certs: false
    loop: "{{ aap_organizations }}"
    register: created_users
    
  - name: Debug created_users
    debug:
      var: created_users