---
  # - name: create aap organizations
  #   infra.aap_configuration.organizations:
  #     aap_organizations: "{{ aap_organizations }}"
  #     aap_hostname: "{{ aap_url }}"
  #     aap_username: "admin"
  #     aap_password: "{{ aap_password }}"
  #     validate_certs: no
  #   register: org_creation
  - name: Create Organization
    ansible.platform.organization:
      name: "{{ aap_organizations.item.name }}"
      description: "{{ aap_organizations.item.name }}"
      gateway_username: "admin"
      gateway_password: "{{ aap_password }}"
      gateway_validate_certs: false
      state: present